# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[[products]]
name = "Joybrau"
flavour = "Lemon"

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
temp_targets = { cpu = 79.5, case = 72.0 }

[database.connection]
host = 1
port = 2

[servers]
db = "mongodb"
[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"

[bananas]
name = "Chiquita"
price = 1.99
quantity = 10

[bananas.color]
red = 0
green = 0.5
blue = 0

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]