# Rust configuration file

title = "Rust"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.64.0"  # MSRV
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "benches/**/*",
  "examples/**/*",
  "tests/**/*"
]

[workspace]
members = ["crates/*"]
resolver = "2"


[profile.release]
debug = 1

[profile.dev]
opt-level = 1


[profile]
panic = "abort"
lto = true